source 'https://api.berkshelf.com'
cookbook  'yum'
cookbook  'yum-epel'
cookbook  'ntp'
cookbook  'apt'
cookbook  'python'
cookbook  'chef-server'
cookbook  'build-essential'
cookbook  'rbenv'
cookbook  'micro-qa', :path => "./cookbooks/micro-qa/"
