name             'micro-qa'
maintainer       'Eucalyptus Systems'
maintainer_email 'vic.iglesias@eucalyptus.com'
license          'Apache 2'
description      'Installs/Configures micro-qa'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends  'dmg'
depends  'git'
depends  'yum'
depends  'yum-epel'
depends  'ntp'
depends  'apt'
depends  'python'
depends  'chef_handler'
depends  'build-essential'
